config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
match 'issues/:id/redmine_zendesk_issue_bridge', :to => 'redmine_zendesk_issue_bridge#index', :via => 'get'
put '/update_ticket_status/:ticket_id', to: 'redmine_zendesk_issue_bridge#update_ticket_status', as: 'update_ticket_status'
put '/update_ticket_field_value/:ticket_id', to: 'redmine_zendesk_issue_bridge#update_ticket_field_value', as: 'update_ticket_field_value'

app/controllers/redmine_zendesk_issue_bridge_controller.rb
# Redmine Zendesk Issue Bridge Controller
class RedmineZendeskIssueBridgeController < ApplicationController
  unloadable

  layout false
  before_action :require_login

  def index
    @zendesk_subdomain = Issue.zendesk_settings[:zendesk_subdomain]
    @related_zendesk_tickets = related_zendesk_tickets()
  end

  def update_ticket_status
    ticket_id = params[:ticket_id]
    ticket = zendesk_client.tickets.find(id: ticket_id)
    if ticket
      status = params[:status]

      if status == 'hold'
        ticket.status = 'hold'
      elsif status == 'open'
        ticket.status = 'open'
      else
        render json: { success: false, message: 'Invalid status value.'}
        return
      end
      ticket.save
      render json: { success: true, message: 'Ticket status updated successfully.' }
    else
      Rails.logger.info("Ticket status: fail")
      render json: { success: false, message: 'Ticket not found.' }
    end
  end

  def update_ticket_field_value
      ticket_id = params[:ticket_id]
      ticket = zendesk_client.tickets.find(id: ticket_id)
      Rails.logger.info("Ticket found: #{ticket.inspect}")
      if ticket
        issueNumber = params[:issueNumber]
        ticket.custom_fields = [
          { id: 'custom_ticket_number', value: issueNumber }
        ]
        ticket.save
      end
  end

private
	def related_zendesk_tickets
		tickets = []
		retrieved = zendesk_client.search query: "fieldvalue:#{params[:id]}"
                if retrieved.empty?
                else
                  retrieved.each do |ticket|
                    next if tickets.any? { |t| t[:id] == ticket[:id] }
                    Rails.logger.info("Adding Ticket ID: #{ticket[:id]}")
                    tickets << ticket if matches_on_custom_field?(ticket[:fields])
                  end
                end
		tickets
	rescue
		[]
	end

	def zendesk_subdomain
		Issue.zendesk_settings[:zendesk_subdomain]
	end

	##
	# Match on Custom Field
	def matches_on_custom_field?(custom_fields = [])
		custom_fields.each do |f|
			next if f.id != Issue.zendesk_settings[:zendesk_custom_field_id].to_i
			next if f.value.nil?
			tickets = f.value.split(/,\s?/).map(&:strip)
			return true if tickets.include?(params[:id].to_s)
		end
		false
	end

	##
	# Zendesk Client
	def zendesk_client
		require 'zendesk_api'
		ZendeskAPI::Client.new do |config|
			subdomain = Issue.zendesk_settings[:zendesk_subdomain]
			config.url = "https://elandsystems.zendesk.com/api/v2" # e.g. https://mydesk.zendesk.com/api/v2
                        config.username = "your zendesk username/token"
                        config.token = "your zendesk token"
                        config.retry = true
		end
	end

end

app/views/issues/_redmine_zendesk_issue_bridge_container.html.erb
<div id="redmine_zendesk_issue_bridge">
	<hr />
	<p>
	  <strong>Related Zendesk Tickets <%= image_tag 'spinner.gif', :plugin => 'redmine_zendesk_issue_bridge' %></strong>
	</p>
</div>

<script type="text/javascript">
$.get("<%= issue_url(params[:id]) %>/redmine_zendesk_issue_bridge", function(data){
	$( '#redmine_zendesk_issue_bridge' ).html( data );
})
</script>

app/views/redmine_zendesk_issue_bridge/index.html.erb
<hr />
<p>
  <label for="ticket-id">Zendesk Ticket ID:</label>
  <input type="text" id="ticket-id" name="ticket_id">
  <button onclick="submitZendeskTicketId(event)">connect</button>
</p>
<p>
  <strong>Related Zendesk Tickets (<%= @related_zendesk_tickets.count %>)</strong>
</p>
<% if @related_zendesk_tickets.count > 0 %>
<table class="list issues">
  <thead>
    <tr>
      <th>Zendesk ID</th>
      <th>Status</th>
      <th>Subject</th>
      <th>Assigned</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Disconnect</th>
      <th>ticket status change</th>
    </tr>
  </thead>
  <tbody>
    <% @related_zendesk_tickets.each do |ticket| %>
    <tr>
      <td class="id"><%= link_to ticket[:id], "https://#{@zendesk_subdomain}.zendesk.com/agent/tickets/#{ticket[:id]}", target: '_blank' %></td>
      <td class="status"><%= ticket[:status] %></td>
      <td class="subject"><%= link_to ticket[:subject], "https://#{@zendesk_subdomain}.zendesk.com/agent/tickets/#{ticket[:id]}", target: '_blank' %></td>
      <% if ticket[:assignee] && ticket[:group] %>
      <td class="assignee_id"><%= mail_to ticket[:assignee][:email], ticket[:assignee][:name], title: ticket[:group][:name] %></td>
      <% elsif ticket[:group] %>
      <td class="assignee_id"><%= ticket[:group][:name] %></td>
      <% else %>
      <td class="assignee_id">(Unassigned)</td>
      <% end %>
      <td class="created_at"><span title="<%= ticket[:created_at] %>"><%= ticket[:created_at].strftime('%m/%d/%Y') %></span></td>
      <td class="updated_at"><span title="<%= ticket[:updated_at] %>"><%= ticket[:updated_at].strftime('%m/%d/%Y') %></span></td>
      <td>
        <button class="disconnect-button" data-ticket-id="<%= ticket[:id] %>" onclick="confirmDisconnect(event)">Disconnect</button>
      </td>
      <% if ticket[:status] == 'open' %>
	<td>
	  <button class="pending-button" data-ticket-id="<%= ticket[:id] %>" onclick="confirmPending(event)">hold</button>
	</td>
      <% elsif ticket[:status] == 'hold' %>
	<td>
	  <button class="open-button" data-ticket-id="<%= ticket[:id] %>" onclick="confirmOpen(event)">open</button>
	</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <p>No related tickets.</p>
<% end %>

<script>
  function confirmDisconnect(event){
    if(confirm('Disconnect?')){
      var button = event.target;
      var ticketId = button.getAttribute('data-ticket-id');
      handleButtonDisconnect(event, ticketId);
    }
    else{
      event.preventDefault();
    }
  }

  function handleButtonDisconnect(event, ticketId){
    fetch('/update_ticket_field_value/' + ticketId, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': '<%= form_authenticity_token %>'
      },
      body: JSON.stringify({ issueNumber: "" })
    })
    .then(response => {
      if (response.ok) {


      } else {

      }
    })
    .catch(error => {

    });
  }


  function confirmOpen(event){
    if(confirm('open your ticket?')){
      handleButtonClick(event, 'open');
    }
    else{
      event.preventDefault();
    }
  }

  function confirmPending(event) {
    if (confirm('hold your ticket?')) {
      handleButtonClick(event, 'hold');
    }
    else{
      event.preventDefault();
    }
  }

  function handleButtonClick(event, status) {
    var button = event.target;
    var ticketId = button.getAttribute('data-ticket-id');

    fetch('/update_ticket_status/' + ticketId, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': '<%= form_authenticity_token %>'
      },
      body: JSON.stringify({ status: status })
    })
    .then(response => {
      if (response.ok) {

      } else {

      }
    })
    .catch(error => {

    });
  }

  function submitZendeskTicketId(event){
    event.preventDefault();
    var ticketId = document.getElementById('ticket-id').value;

    var currentURL = window.location.href;
    var regex = /\/(\d+)/;
    var match = currentURL.match(regex);
    var issueNumber = match ? match[1] : "";

    // AJAX 요청을 통해 서버로 상태 값을 업데이트합니다.
    fetch('/update_ticket_field_value/' + ticketId, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': '<%= form_authenticity_token %>'
      },
      body: JSON.stringify({ issueNumber: issueNumber })
    })
    .then(response => {
      if (response.ok) {

      } else {

      }
    })
    .catch(error => {

    });

  }

</script>

app/views/settings/_zendesk_settings.html.erb
<table>
  <tbody>
    <tr>
      <th>Custom Field ID</th>
      <td>
        <input type="text" id="settings_zendesk_custom_field_id" value="<%= settings['zendesk_custom_field_id'] %>" name="settings[zendesk_custom_field_id]" />
      </td>
    </tr>
    <tr>
      <td colspan="2"><hr /><td>
    </tr>
    <th>Zendesk Subdomain</th>
      <td>
        <input type="text" id="settings_zendesk_subdomain" value="<%= settings['zendesk_subdomain'] %>" name="settings[zendesk_subdomain]" />
      </td>
    </tr>
    <tr>
      <th>Username</th>
      <td>
        <input type="zendesk_username" id="settings_zendesk_username" value="<%= settings['zendesk_username'] %>" name="settings[zendesk_username]" />
      </td>
    </tr>
    <tr>
      <th>Password</th>
      <td>
        <input type="zendesk_passwrd" id="settings_zendesk_password" value="<%= settings['zendesk_password'] %>" name="settings[zendesk_password]" />
      </td>
    </tr>
  </tbody>
</table>